# Generated by Django 5.0.6 on 2024-06-23 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.IntegerField(unique=True, verbose_name='DNI')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ISBN', models.CharField(max_length=100, unique=True, verbose_name='ISBN')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('autor', models.CharField(max_length=100, verbose_name='Autor')),
                ('precio', models.IntegerField(verbose_name='Precio')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido', models.CharField(max_length=100, verbose_name='Pedido')),
                ('fechaPedido', models.DateField(verbose_name='Fecha de Pedido')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.libro')),
            ],
        ),
    ]
